Repository web-infra-dev/rslib, pull requests merged in 2024-12, with the labels that each got.

#510 fix: catch error when killing DTS child process
  packages/plugin-dts/src/index.ts
Labels: change: fix

#518 feat: support load env
  .gitignore
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  pnpm-lock.yaml
  tests/integration/cli/env/.env
  tests/integration/cli/env/.env.test
  tests/integration/cli/env/env.test.ts
  tests/integration/cli/env/env/.env
  tests/integration/cli/env/package.json
  tests/integration/cli/env/rslib.config.ts
  tests/integration/cli/env/src/index.ts
  website/docs/en/guide/basic/cli.mdx
Labels: change: feat

#520 feat: do not preserve nodeEnv when format is umd
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  tests/integration/umd/index.test.ts
  tests/integration/umd/src/index.js
  tests/integration/umd/src/utils.js
  website/docs/en/guide/basic/cli.mdx
Labels: change: feat

#516 fix(create-rslib): set tsconfig jsx to `react-jsx`
  examples/react-component-bundle-false/rslib.config.ts
  examples/react-component-bundle-false/tsconfig.json
  examples/react-component-bundle/rslib.config.ts
  examples/react-component-bundle/tsconfig.json
  examples/react-component-umd/rslib.config.ts
  examples/react-component-umd/tsconfig.json
  packages/create-rslib/fragments/base/react-js/rslib.config.mjs
  packages/create-rslib/fragments/base/react-ts/rslib.config.ts
  packages/create-rslib/fragments/base/react-ts/tsconfig.json
  packages/create-rslib/template-[react]-[]-js/rslib.config.mjs
  packages/create-rslib/template-[react]-[]-ts/rslib.config.ts
  packages/create-rslib/template-[react]-[]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[storybook,vitest]-js/rslib.config.mjs
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/rslib.config.ts
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[storybook]-js/rslib.config.mjs
  packages/create-rslib/template-[react]-[storybook]-ts/rslib.config.ts
  packages/create-rslib/template-[react]-[storybook]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[vitest]-js/rslib.config.mjs
  packages/create-rslib/template-[react]-[vitest]-ts/rslib.config.ts
  packages/create-rslib/template-[react]-[vitest]-ts/tsconfig.json
Labels: change: fix

#523 docs: translate cli.mdx to Chinese
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: docs

#524 docs: translate some basic and advanced docs
  website/docs/en/guide/advanced/output-compatibility.mdx
  website/docs/en/guide/advanced/third-party-deps.mdx
  website/docs/en/guide/basic/output-format.mdx
  website/docs/en/guide/basic/output-structure.mdx
  website/docs/en/guide/basic/typescript.mdx
  website/docs/en/guide/basic/upgrade-rslib.mdx
  website/docs/zh/guide/advanced/output-compatibility.mdx
  website/docs/zh/guide/advanced/third-party-deps.mdx
  website/docs/zh/guide/basic/output-format.mdx
  website/docs/zh/guide/basic/output-structure.mdx
  website/docs/zh/guide/basic/typescript.mdx
  website/docs/zh/guide/basic/upgrade-rslib.mdx
  website/docs/zh/guide/start/components/CJS.mdx
  website/docs/zh/guide/start/components/ESM.mdx
  website/docs/zh/guide/start/components/MF.mdx
  website/docs/zh/guide/start/components/UMD.mdx
Labels: change: docs

#525 docs: translate migration docs
  website/docs/en/guide/migration/modernjs-module.mdx
  website/docs/en/guide/migration/tsup.mdx
  website/docs/zh/guide/advanced/output-compatibility.mdx
  website/docs/zh/guide/basic/output-structure.mdx
  website/docs/zh/guide/migration/modernjs-module.mdx
  website/docs/zh/guide/migration/tsup.mdx
Labels: change: docs

#526 docs(zh): translate /config/lib to Chinese
  packages/core/src/types/config/index.ts
  website/docs/en/config/lib/auto-extension.mdx
  website/docs/en/config/lib/auto-external.mdx
  website/docs/en/config/lib/banner.mdx
  website/docs/en/config/lib/dts.mdx
  website/docs/en/config/lib/external-helpers.mdx
  website/docs/en/config/lib/footer.mdx
  website/docs/en/config/lib/format.mdx
  website/docs/en/config/lib/shims.mdx
  website/docs/en/config/lib/syntax.mdx
  website/docs/zh/config/lib/auto-extension.mdx
  website/docs/zh/config/lib/auto-external.mdx
  website/docs/zh/config/lib/banner.mdx
  website/docs/zh/config/lib/bundle.mdx
  website/docs/zh/config/lib/dts.mdx
  website/docs/zh/config/lib/external-helpers.mdx
  website/docs/zh/config/lib/footer.mdx
  website/docs/zh/config/lib/format.mdx
  website/docs/zh/config/lib/id.mdx
  website/docs/zh/config/lib/redirect.mdx
  website/docs/zh/config/lib/shims.mdx
  website/docs/zh/config/lib/syntax.mdx
  website/docs/zh/config/lib/umd-name.mdx
Labels: change: docs

#528 docs: translate configure-rslib
  website/docs/en/guide/basic/configure-rslib.mdx
  website/docs/zh/guide/basic/configure-rslib.mdx
Labels: change: docs

#529 docs: preserve footer keyword
  website/docs/zh/config/lib/footer.mdx
Labels: change: docs

#543 docs: translate Rsbuild configurations
  website/docs/en/config/rsbuild/index.mdx
  website/docs/en/config/rsbuild/output.mdx
  website/docs/en/config/rsbuild/resolve.mdx
  website/docs/en/config/rsbuild/source.mdx
  website/docs/en/config/rsbuild/tools.mdx
  website/docs/zh/config/rsbuild/index.mdx
  website/docs/zh/config/rsbuild/output.mdx
  website/docs/zh/config/rsbuild/resolve.mdx
  website/docs/zh/config/rsbuild/source.mdx
  website/docs/zh/config/rsbuild/tools.mdx
Labels: change: docs

#546 docs: fix website broken by React 19
  pnpm-lock.yaml
  website/package.json
Labels: change: docs

#549 docs: translate plugins configuration
  website/docs/en/config/rsbuild/plugins.mdx
  website/docs/zh/config/rsbuild/plugins.mdx
Labels: change: docs

#551 docs(zh): translate other zh docs
  website/docs/en/guide/advanced/dts.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/solution/index.mdx
  website/docs/en/guide/solution/nodejs.mdx
  website/docs/en/guide/solution/react.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/advanced/dts.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
  website/docs/zh/guide/solution/index.mdx
  website/docs/zh/guide/solution/nodejs.mdx
  website/docs/zh/guide/solution/react.mdx
  website/docs/zh/guide/start/glossary.mdx
  website/docs/zh/guide/start/npm-packages.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/theme/index.tsx
Labels: change: docs

#552 fix: shared Rsbuild plugins should run only once
  packages/core/src/cli/build.ts
  packages/core/src/cli/inspect.ts
  packages/core/src/cli/mf.ts
  packages/core/src/config.ts
  packages/core/src/utils/helper.ts
  pnpm-lock.yaml
  tests/integration/plugins/index.test.ts
  tests/integration/plugins/package.json
  tests/integration/plugins/rslib.config.ts
  tests/integration/plugins/src/index.ts
Labels: change: fix

#554 docs(zh): translate use storybook
  website/docs/en/guide/advanced/storybook.mdx
  website/docs/zh/guide/advanced/storybook.mdx
Labels: change: docs

#556 fix: zh docs links
  website/docs/zh/guide/advanced/storybook.mdx
Labels: change: fix

#557 fix(create-rslib): correctly resolve `storybook-addon-rslib` in pnpm
  packages/create-rslib/fragments/tools/storybook-react-js/.storybook/main.js
  packages/create-rslib/fragments/tools/storybook-react-ts/.storybook/main.ts
  packages/create-rslib/template-[react]-[storybook,vitest]-js/.storybook/main.js
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/.storybook/main.ts
  packages/create-rslib/template-[react]-[storybook]-js/.storybook/main.js
  packages/create-rslib/template-[react]-[storybook]-ts/.storybook/main.ts
Labels: change: fix

#522 fix(minify): only preserve some comments and annotations by default
  examples/module-federation/mf-host/package.json
  examples/module-federation/mf-remote/package.json
  packages/core/package.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/config.test.ts
  packages/create-rslib/fragments/tools/storybook-react-js/package.json
  packages/create-rslib/fragments/tools/storybook-react-ts/package.json
  packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
  packages/create-rslib/template-[react]-[storybook]-js/package.json
  packages/create-rslib/template-[react]-[storybook]-ts/package.json
  packages/plugin-dts/package.json
  pnpm-lock.yaml
  tests/integration/asset/__snapshots__/index.test.ts.snap
  tests/integration/bundle-false/__snapshots__/index.test.ts.snap
  tests/integration/extension-alias/__snapshots__/index.test.ts.snap
  tests/integration/minify/__fixtures__/src/index.ts
  tests/integration/minify/config/disabled/package.json
  tests/integration/minify/config/disabled/rslib.config.ts
  tests/integration/minify/config/enabled/package.json
  tests/integration/minify/config/enabled/rslib.config.ts
  tests/integration/minify/default/rslib.config.ts
  tests/integration/minify/index.test.ts
  tests/integration/minify/mf/config/rslib.config.ts
  tests/integration/minify/mf/default/rslib.config.ts
  tests/integration/resolve/index.test.ts
  tests/integration/shims/index.test.ts
  tests/package.json
  website/docs/en/guide/_meta.json
  website/docs/en/guide/faq/_meta.json
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/_meta.json
  website/docs/zh/guide/faq/_meta.json
  website/docs/zh/guide/faq/features.mdx
  website/package.json
Labels: change: fix

#564 docs: config name typo
  website/docs/en/guide/solution/nodejs.mdx
  website/docs/zh/guide/solution/nodejs.mdx
Labels: change: docs

#565 docs: correct config position level
  website/docs/en/config/lib/external-helpers.mdx
  website/docs/en/config/lib/syntax.mdx
  website/docs/zh/config/lib/external-helpers.mdx
  website/docs/zh/config/lib/syntax.mdx
Labels: change: docs

#568 fix: type missing when set moduleResolution node16+
  packages/core/rslib.config.ts
Labels: change: fix

#571 docs(plugins): add publint plugin
  website/docs/en/config/rsbuild/plugins.mdx
  website/docs/zh/config/rsbuild/plugins.mdx
Labels: change: docs

#573 feat(css): support css asset in bundle mode and esm/cjs
  examples/react-component-bundle/rslib.config.ts
  examples/react-component-bundle/src/assets/logo.svg
  examples/react-component-bundle/src/index.scss
  examples/react-component-bundle/src/index.tsx
  packages/core/src/asset/assetConfig.ts
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  tests/e2e/react-component/index.pw.test.ts
  tests/e2e/react-component/rsbuild.config.ts
  tests/integration/asset/limit/rslib.config.ts
  tests/integration/style/sass/__fixtures__/src/foundation/index.scss
  tests/integration/style/sass/__fixtures__/src/index.scss
  tests/integration/style/sass/bundle/rslib.config.ts
  tests/integration/style/sass/index.test.ts
Labels: change: feat

#582 feat(css): support css asset in bundleless mode and esm/cjs
  examples/react-component-bundle-false/rslib.config.ts
  examples/react-component-bundle-false/src/assets/logo.svg
  examples/react-component-bundle-false/src/index.scss
  examples/react-component-bundle-false/src/index.tsx
  packages/core/src/asset/assetConfig.ts
  packages/core/src/css/LibCssExtractPlugin.ts
  packages/core/src/css/RemoveCssExtractAssetPlugin.ts
  packages/core/src/css/cssConfig.ts
  packages/core/src/css/libCssExtractLoader.ts
  packages/core/src/css/utils.ts
  tests/e2e/react-component/index.pw.test.ts
  tests/integration/asset/limit/rslib.config.ts
  tests/integration/style/sass/bundle-false/rslib.config.ts
Labels: change: feat

#584 fix: pass server config to Rsbuild
  packages/core/src/cli/build.ts
  packages/core/src/cli/inspect.ts
  packages/core/src/cli/mf.ts
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/server/basic/package.json
  tests/integration/server/basic/public/logo.svg
  tests/integration/server/basic/rslib.config.ts
  tests/integration/server/basic/src/index.ts
  tests/integration/server/index.test.ts
  tests/integration/server/mf-dev/package.json
  tests/integration/server/mf-dev/rslib.config.ts
  tests/integration/server/mf-dev/src/index.ts
Labels: change: fix

#590 feat!: support `--lib` param of `mf-dev` command
  examples/module-federation/mf-react-component/package.json
  examples/module-federation/mf-react-component/rslib.config.ts
  packages/core/src/asset/assetConfig.ts
  packages/core/src/cli/build.ts
  packages/core/src/cli/commands.ts
  packages/core/src/cli/inspect.ts
  packages/core/src/cli/mf.ts
  packages/core/src/config.ts
  packages/core/src/css/cssConfig.ts
  packages/core/src/plugins/EntryChunkPlugin.ts
  packages/core/src/types/config.ts
  packages/core/src/types/utils.ts
  packages/core/src/utils/syntax.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/config.test.ts
  pnpm-lock.yaml
  tests/integration/cli/build/build.test.ts
  tests/integration/cli/build/custom-root/rslib.config.ts
  tests/integration/cli/mf-dev/dev.test.ts
  tests/integration/cli/mf-dev/package.json
  tests/integration/cli/mf-dev/rslib.config.ts
  tests/integration/cli/mf-dev/src/index.ts
  tests/integration/plugins/basic/package.json
  tests/integration/plugins/basic/rslib.config.ts
  tests/integration/plugins/basic/src/index.ts
  tests/integration/plugins/index.test.ts
  tests/integration/plugins/mf-dev/package.json
  tests/integration/plugins/mf-dev/rslib.config.ts
  tests/integration/plugins/mf-dev/src/index.ts
  tests/integration/server/index.test.ts
  tests/integration/server/mf-dev/rslib.config.ts
  tests/playwright.config.ts
  website/docs/en/config/lib/index.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/config/lib/index.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#598 docs: modify release steps
  CONTRIBUTING.md
Labels: change: docs

#602 fix: adapt @rspack/core 1.1.9
  package.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
  tests/integration/alias/__snapshots__/index.test.ts.snap
  tests/integration/alias/index.test.ts
  tests/integration/asset/__snapshots__/index.test.ts.snap
  tests/integration/auto-external/index.test.ts
  tests/integration/bundle-false/__snapshots__/index.test.ts.snap
  tests/integration/bundle-false/index.test.ts
  tests/integration/external-helpers/__snapshots__/index.test.ts.snap
  tests/integration/externals/index.test.ts
  tests/integration/format/index.test.ts
  tests/integration/minify/index.test.ts
  tests/integration/redirect/js.test.ts
  tests/integration/require/index.test.ts
  tests/integration/resolve/index.test.ts
  tests/integration/shims/index.test.ts
  tests/integration/transform-import/index.test.ts
Labels: change: fix

#607 fix(create-rslib): remove unnecessary React import
  examples/module-federation/mf-react-component/stories/index.stories.tsx
  examples/react-component-bundle-false/src/components/CounterButton/index.tsx
  examples/react-component-bundle-false/src/index.tsx
  examples/react-component-bundle/src/components/CounterButton/index.tsx
  examples/react-component-bundle/src/index.tsx
  packages/create-rslib/fragments/base/react-js/src/Button.jsx
  packages/create-rslib/fragments/base/react-ts/src/Button.tsx
  packages/create-rslib/fragments/tools/vitest-node-ts/tests/tsconfig.json
  packages/create-rslib/fragments/tools/vitest-react-js/tests/index.test.jsx
  packages/create-rslib/fragments/tools/vitest-react-ts/tests/index.test.tsx
  packages/create-rslib/fragments/tools/vitest-react-ts/tests/tsconfig.json
  packages/create-rslib/template-[node-dual]-[vitest]-ts/tests/tsconfig.json
  packages/create-rslib/template-[node-esm]-[vitest]-ts/tests/tsconfig.json
  packages/create-rslib/template-[react]-[]-js/src/Button.jsx
  packages/create-rslib/template-[react]-[]-ts/src/Button.tsx
  packages/create-rslib/template-[react]-[storybook,vitest]-js/src/Button.jsx
  packages/create-rslib/template-[react]-[storybook,vitest]-js/tests/index.test.jsx
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/src/Button.tsx
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/tests/index.test.tsx
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/tests/tsconfig.json
  packages/create-rslib/template-[react]-[storybook]-js/src/Button.jsx
  packages/create-rslib/template-[react]-[storybook]-ts/src/Button.tsx
  packages/create-rslib/template-[react]-[vitest]-js/src/Button.jsx
  packages/create-rslib/template-[react]-[vitest]-js/tests/index.test.jsx
  packages/create-rslib/template-[react]-[vitest]-ts/src/Button.tsx
  packages/create-rslib/template-[react]-[vitest]-ts/tests/index.test.tsx
  packages/create-rslib/template-[react]-[vitest]-ts/tests/tsconfig.json
Labels: change: fix

#609 fix: mf-dev should apply correct config
  examples/module-federation/mf-react-component/rslib.config.ts
  examples/module-federation/mf-react-component/tsconfig.build.json
  packages/core/package.json
  packages/core/src/cli/mf.ts
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/config.test.ts
  pnpm-lock.yaml
  tests/integration/cli/mf-dev/dev.test.ts
  tests/integration/cli/mf-dev/rslib.config.ts
  tests/integration/cli/mf/build/package.json
  tests/integration/cli/mf/build/rslib.config.ts
  tests/integration/cli/mf/build/src/index.ts
  tests/integration/cli/mf/dev/package.json
  tests/integration/cli/mf/dev/rslib.config.ts
  tests/integration/cli/mf/dev/src/index.ts
  tests/integration/cli/mf/mf.test.ts
  tests/integration/plugins/mf-dev/rslib.config.ts
  tests/integration/server/index.test.ts
  tests/integration/server/mf-dev/rslib.config.ts
Labels: change: fix

#612 fix: do not handle the path that can’t be resolved
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/redirect/js-not-resolve/package.json
  tests/integration/redirect/js-not-resolve/rslib.config.ts
  tests/integration/redirect/js-not-resolve/src/index.js
  tests/integration/redirect/js.test.ts
  tests/integration/redirect/jsNotResolved.test.ts
  tests/scripts/shared.ts
Labels: change: fix

#623 docs: add how to skip the preprocessing of `less/scss` files
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: change: docs

#624 feat!: disable `autoExternal` in bundleless mode and only redirect request not in node_modules
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/auto-external/bundle-false/package.json
  tests/integration/auto-external/bundle-false/rslib.config.ts
  tests/integration/auto-external/bundle-false/src/index.ts
  tests/integration/auto-external/bundle-false/tsconfig.json
  tests/integration/auto-external/index.test.ts
  tests/integration/redirect/js-not-resolve/src/index.js
  tests/integration/redirect/js.test.ts
  tests/integration/redirect/js/src/index.ts
  tests/integration/redirect/jsNotResolved.test.ts
  website/docs/en/config/lib/auto-external.mdx
  website/docs/en/config/lib/redirect.mdx
  website/docs/en/guide/advanced/third-party-deps.mdx
  website/docs/zh/config/lib/auto-external.mdx
  website/docs/zh/config/lib/redirect.mdx
  website/docs/zh/guide/advanced/third-party-deps.mdx
Labels: change: feat
