Repository web-infra-dev/rslib, pull requests merged in 2024-09, with the labels that each got.

#163 fix: syntax could handle combined pattern
  e2e/cases/syntax/__snapshots__/index.test.ts.snap
  e2e/cases/syntax/config/rslib.config.ts
  e2e/cases/syntax/index.test.ts
  packages/core/src/config.ts
  packages/core/src/utils/syntax.ts
  packages/core/tests/syntax.test.ts
Labels: change: fix

#168 fix(create-rslib): broken shebang line in bin file
  packages/create-rslib/bin.js
  packages/create-rslib/package.json
  packages/create-rslib/src/index.ts
Labels: change: fix

#164 fix: could accept minify from user
  e2e/cases/minify/config/package.json
  e2e/cases/minify/config/rslib.config.ts
  e2e/cases/minify/config/src/index.ts
  packages/core/src/config.ts
  packages/core/tests/config.test.ts
  pnpm-lock.yaml
Labels: change: fix

#169 feat!: move config `output.syntax` to `syntax`
  e2e/cases/syntax/config/rslib.config.ts
  packages/core/rslib.config.ts
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/core/tests/config.test.ts
Labels: change: feat

#171 feat: support `externalHelpers`
  e2e/cases/external-helpers/__fixtures__/src/index.ts
  e2e/cases/external-helpers/__fixtures__/tsconfig.json
  e2e/cases/external-helpers/__snapshots__/index.test.ts.snap
  e2e/cases/external-helpers/config-override/package.json
  e2e/cases/external-helpers/config-override/rslib.config.ts
  e2e/cases/external-helpers/default/package.json
  e2e/cases/external-helpers/default/rslib.config.ts
  e2e/cases/external-helpers/index.test.ts
  e2e/cases/external-helpers/no-deps/package.json
  e2e/cases/external-helpers/no-deps/rslib.config.ts
  e2e/cases/external-helpers/true/package.json
  e2e/cases/external-helpers/true/rslib.config.ts
  e2e/cases/syntax/__snapshots__/index.test.ts.snap
  packages/core/src/config.ts
  packages/core/src/constant.ts
  packages/core/src/types/config/index.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#174 fix: should remain process.env.NODE_ENV as is by default
  e2e/cases/auto-external/index.test.ts
  e2e/cases/define/index.test.ts
  e2e/cases/define/rslib.config.ts
  e2e/cases/define/src/index.ts
  e2e/scripts/shared.ts
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
Labels: change: fix

#175 feat: support `banner` and `footer`
  .changeset/nice-hotels-cheer.md
  e2e/cases/banner-footer/index.test.ts
  e2e/cases/banner-footer/package.json
  e2e/cases/banner-footer/rslib.config.ts
  e2e/cases/banner-footer/src/foo.ts
  e2e/cases/banner-footer/src/index.css
  e2e/cases/banner-footer/src/index.ts
  e2e/cases/banner-footer/tsconfig.json
  e2e/cases/extension-alias/rslib.config.ts
  e2e/scripts/shared.ts
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/core/src/utils/helper.ts
  packages/plugin-dts/package.json
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#185 docs: init Rslib website
  pnpm-lock.yaml
  pnpm-workspace.yaml
  website/LICENSE
  website/README.md
  website/docs/en/_meta.json
  website/docs/en/guide/_meta.json
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/configure-rslib.mdx
  website/docs/en/guide/start/_meta.json
  website/docs/en/guide/start/features.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/index.mdx
  website/docs/public/netlify.toml
  website/docs/zh/_meta.json
  website/docs/zh/guide/_meta.json
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/configure-rslib.mdx
  website/docs/zh/guide/start/_meta.json
  website/docs/zh/guide/start/features.mdx
  website/docs/zh/guide/start/index.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/index.mdx
  website/env.d.ts
  website/i18n.json
  website/package.json
  website/rspress.config.ts
  website/theme/components/Copyright.module.scss
  website/theme/components/Copyright.tsx
  website/theme/components/Hero.module.scss
  website/theme/components/Hero.tsx
  website/theme/components/NextSteps.module.scss
  website/theme/components/NextSteps.tsx
  website/theme/components/Overview.module.scss
  website/theme/components/Overview.tsx
  website/theme/components/Step.module.scss
  website/theme/components/Step.tsx
  website/theme/components/ToolStack.tsx
  website/theme/components/utils.ts
  website/theme/env.d.ts
  website/theme/index.scss
  website/theme/index.tsx
  website/theme/pages/index.tsx
  website/tsconfig.json
Labels: change: docs

#189 feat: set legacy decorators version when `experimentalDecorators` enabled
  e2e/README.md
  e2e/cases/decorators/__fixtures__/src/index.ts
  e2e/cases/decorators/__fixtures__/tsconfig.decorators.json
  e2e/cases/decorators/__fixtures__/tsconfig.json
  e2e/cases/decorators/__snapshots__/index.test.ts.snap
  e2e/cases/decorators/default/package.json
  e2e/cases/decorators/default/rslib.config.ts
  e2e/cases/decorators/index.test.ts
  e2e/cases/decorators/tsconfig/package.json
  e2e/cases/decorators/tsconfig/rslib.config.ts
  e2e/cases/tsconfig/index.test.ts
  e2e/cases/tsconfig/package.json
  e2e/cases/tsconfig/rslib.config.ts
  e2e/cases/tsconfig/src/foo.ts
  e2e/cases/tsconfig/src/index.ts
  e2e/cases/tsconfig/tsconfig.custom.json
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/rslib.config.ts
  packages/core/src/config.ts
  packages/core/src/utils/tsconfig.ts
  packages/core/tests/extension.test.ts
  packages/core/tests/fixtures/tsconfig/exist/tsconfig.custom.json
  packages/core/tests/fixtures/tsconfig/exist/tsconfig.json
  packages/core/tests/fixtures/tsconfig/no-exist/index.js
  packages/core/tests/tsconfig.test.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: feat

#191 fix: should resolve esnext browserslist
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/core/src/utils/syntax.ts
  packages/core/tests/syntax.test.ts
Labels: change: fix

#200 docs: update domain
  packages/core/README.md
  packages/core/package.json
  packages/create-rslib/README.md
  packages/create-rslib/package.json
  packages/plugin-dts/README.md
  packages/plugin-dts/package.json
Labels: change: docs

#213 fix: derive `rspack.target` from `libConfig.syntax`
  e2e/cases/syntax/index.test.ts
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
Labels: change: fix

#216 feat: support `import.meta.url` shim for CJS
  e2e/cases/shims/cjs/package.json
  e2e/cases/shims/cjs/rslib.config.ts
  e2e/cases/shims/cjs/src/index.ts
  e2e/cases/shims/index.test.ts
  packages/core/src/config.ts
  packages/core/src/plugins/cjsShim.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#234 fix: CJS shims should not affect other environments
  e2e/cases/shims/cjs/rslib.config.ts
  e2e/cases/shims/index.test.ts
  packages/core/src/plugins/cjsShim.ts
Labels: change: fix

#237 fix: do not transform esX for rspack.target field
  e2e/cases/shims/esm/rslib.config.ts
  e2e/cases/shims/index.test.ts
  package.json
  packages/core/src/config.ts
  packages/core/src/utils/syntax.ts
  packages/core/tests/syntax.test.ts
Labels: change: fix

#252 docs: setup Google Analytics
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/package.json
  website/rspress.config.ts
Labels: change: docs

#249 fix: preserve require.resolve / dynamic require / dynamic import
  CONTRIBUTING.md
  package.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
  tests/integration/decorators/__snapshots__/index.test.ts.snap
  tests/integration/require/import-dynamic/index.ts
  tests/integration/require/import-dynamic/package.json
  tests/integration/require/import-dynamic/rslib.config.ts
  tests/integration/require/index.test.ts
  tests/integration/require/require-as-expression/index.js
  tests/integration/require/require-as-expression/package.json
  tests/integration/require/require-as-expression/rslib.config.ts
  tests/integration/require/require-dynamic/index.ts
  tests/integration/require/require-dynamic/package.json
  tests/integration/require/require-dynamic/rslib.config.ts
  tests/integration/require/require-resolve/index.ts
  tests/integration/require/require-resolve/package.json
  tests/integration/require/require-resolve/rslib.config.ts
Labels: change: fix
