Repository web-infra-dev/rslib, pull requests merged in 2024-08, with the labels that each got.

#52 fix: browserslist query and rspack target
  CONTRIBUTING.md
  e2e/cases/alias/__snapshots__/index.test.ts.snap
  e2e/scripts/shared.ts
  package.json
  packages/core/src/config.ts
  packages/core/src/utils/syntax.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/config.test.ts
  packages/core/tests/syntax.test.ts
  pnpm-lock.yaml
Labels: change: fix

#57 fix: typo wrong in README
  README.md
Labels: change: fix

#58 feat: print DTS generation time
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/tsc.ts
Labels: change: feat

#64 perf: enable TypeScript isolatedDeclarations
  packages/core/src/build.ts
  packages/core/src/cli/commands.ts
  packages/core/src/cli/prepare.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/core/src/utils/extension.ts
  packages/core/src/utils/helper.ts
  packages/core/src/utils/logger.ts
  packages/core/tsconfig.json
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
  packages/plugin-dts/tsconfig.json
  scripts/tsconfig/base.json
Labels: change: perf

#63 feat(plugin-dts): dtsPromise only registered when firstCompile and print log with environment info
  e2e/package.json
  packages/core/package.json
  packages/plugin-dts/package.json
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/tsc.ts
  pnpm-lock.yaml
Labels: change: feat

#69 feat: support dts.abortOnError
  e2e/cases/dts/bundle-false/abortOnError.config.ts
  e2e/cases/dts/bundle-false/src-error/const.ts
  e2e/cases/dts/bundle-false/src-error/index.ts
  e2e/cases/dts/bundle-false/tsconfig-error.json
  e2e/cases/dts/bundle/abortOnError.config.ts
  e2e/cases/dts/bundle/src-error/const.ts
  e2e/cases/dts/bundle/src-error/index.ts
  e2e/cases/dts/bundle/tsconfig-error.json
  e2e/cases/dts/index.test.ts
  e2e/scripts/shared.ts
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/plugin-dts/src/index.ts
Labels: change: feat

#71 fix: lcp should not be a file path
  biome.json
  e2e/cases/bundle-false/index.test.ts
  e2e/cases/bundle-false/single-file/rslib.config.ts
  e2e/cases/bundle-false/single-file/src/index.ts
  e2e/cases/bundle-false/single-file/tsconfig.json
  e2e/scripts/shared.ts
  e2e/setupVitestTests.ts
  e2e/vitest.config.ts
  package.json
  packages/core/__mocks__/fs.cjs
  packages/core/__mocks__/fs/promises.cjs
  packages/core/package.json
  packages/core/src/config.ts
  packages/core/src/utils/extension.ts
  packages/core/src/utils/helper.ts
  packages/core/tests/helper.test.ts
  packages/core/vitest.config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  vitest.workspace.ts
Labels: change: fix

#73 feat: use "module-import" in ESM
  CONTRIBUTING.md
  package.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#72 feat: support DTS autoExtension
  e2e/cases/dts/__snapshots__/index.test.ts.snap
  e2e/cases/dts/bundle-false/autoExtension.config.ts
  e2e/cases/dts/bundle-false/package.json
  e2e/cases/dts/bundle/autoExtension.config.ts
  e2e/cases/dts/index.test.ts
  examples/express-plugin/rslib.config.ts
  examples/react-component/rslib.config.ts
  packages/core/src/config.ts
  packages/plugin-dts/package.json
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#74 feat(bundle): support autoExternal configuration
  e2e/cases/auto-external/default/package.json
  e2e/cases/auto-external/default/rslib.config.ts
  e2e/cases/auto-external/external-sub-path/package.json
  e2e/cases/auto-external/external-sub-path/rslib.config.ts
  e2e/cases/auto-external/external-sub-path/src/index.ts
  e2e/cases/auto-external/false/package.json
  e2e/cases/auto-external/false/rslib.config.ts
  e2e/cases/auto-external/fixtures/src/index.ts
  e2e/cases/auto-external/index.test.ts
  e2e/cases/auto-external/with-externals/package.json
  e2e/cases/auto-external/with-externals/rslib.config.ts
  examples/express-plugin/rslib.config.ts
  examples/react-component/rslib.config.ts
  packages/core/__mocks__/rslog.cjs
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/core/src/types/index.ts
  packages/core/src/types/utils.ts
  packages/core/src/utils/extension.ts
  packages/core/src/utils/helper.ts
  packages/core/tests/config.test.ts
  packages/core/tests/extension.test.ts
  packages/core/tests/external.test.ts
  packages/core/tests/fixtures/extension/type-commonjs/package.json
  packages/core/tests/fixtures/extension/type-module/package.json
  packages/core/tests/helper.test.ts
  packages/core/tests/lcp.test.ts
  pnpm-lock.yaml
Labels: change: feat

#75 feat: support DTS bundle file name
  e2e/cases/dts/bundle/bundleName.config.ts
  e2e/cases/dts/index.test.ts
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/utils.ts
Labels: change: feat

#80 feat: support autoExternal for dts files
  e2e/cases/auto-external/default/package.json
  e2e/cases/auto-external/default/rslib.config.ts
  e2e/cases/auto-external/default/src/index.ts
  e2e/cases/auto-external/default/tsconfig.json
  e2e/cases/auto-external/false/package.json
  e2e/cases/auto-external/false/rslib.config.ts
  e2e/cases/auto-external/false/src/index.ts
  e2e/cases/auto-external/false/tsconfig.json
  e2e/cases/auto-external/index.test.ts
  e2e/scripts/shared.ts
  package.json
  packages/core/src/config.ts
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/tests/external.test.ts
  packages/plugin-dts/vitest.config.ts
  pnpm-lock.yaml
Labels: change: feat

#78 fix: rootDir in bundle DTS
  e2e/cases/dts/bundle-false/__fixtures__/tsconfig.json
  e2e/cases/dts/bundle-false/abort-on-error/tsconfig.json
  e2e/cases/dts/bundle/__fixtures__/tsconfig.json
  e2e/cases/dts/bundle/abort-on-error/tsconfig.json
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
Labels: change: fix

#83 feat: preserve import.meta.url in ESM
  e2e/cases/shims/esm/rslib.config.ts
  e2e/cases/shims/esm/src/index.ts
  e2e/cases/shims/index.test.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/core/src/types/index.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
Labels: change: feat

#85 feat: align the time log format with Rsbuild
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
Labels: change: feat

#90 feat: add js extension for relative import in bundleless mode
  e2e/cases/bundle-false/index.test.ts
  e2e/cases/bundle-false/relative-import/package.json
  e2e/cases/bundle-false/relative-import/rslib.config.ts
  e2e/cases/bundle-false/relative-import/src/bar.ts
  e2e/cases/bundle-false/relative-import/src/index.ts
  e2e/cases/bundle-false/relative-import/tsconfig.json
  e2e/scripts/shared.ts
  packages/core/src/config.ts
  packages/core/src/utils/helper.ts
  pnpm-lock.yaml
Labels: change: feat

#96 docs: update readme with npm packages and contributors
  README.md
Labels: change: docs

#103 feat: bump rsbuild to support clean inspect configs
  e2e/package.json
  examples/react-component/package.json
  packages/core/package.json
  packages/plugin-dts/package.json
  pnpm-lock.yaml
Labels: change: feat

#105 fix(plugin-dts): undefined named export from typescript package
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
Labels: change: fix

#107 docs(README): unify badges color
  README.md
Labels: change: docs

#108 fix: should respect `output.filename.js` config
  e2e/cases/auto-extension/index.test.ts
  e2e/cases/auto-extension/type-commonjs/config-override/package.json
  e2e/cases/auto-extension/type-commonjs/config-override/rslib.config.ts
  e2e/cases/auto-extension/type-module/config-override/package.json
  e2e/cases/auto-extension/type-module/config-override/rslib.config.ts
  packages/core/src/config.ts
Labels: change: fix

#109 fix(type): import type from 'src'
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/utils.ts
Labels: change: fix

#110 fix(types): import 'src' in core
  packages/core/src/utils/extension.ts
Labels: change: fix

#116 docs: add QoS to README
  README.md
Labels: change: docs

#120 fix: absolute entry when bundle DTS
  e2e/cases/dts/bundle/absolute-entry/package.json
  e2e/cases/dts/bundle/absolute-entry/rslib.config.ts
  e2e/cases/dts/index.test.ts
  packages/plugin-dts/src/dts.ts
Labels: change: fix

#124 feat: add warn when request type bail from "module-import"
  e2e/cases/auto-external/index.test.ts
  e2e/cases/auto-external/module-import-warn/package.json
  e2e/cases/auto-external/module-import-warn/rslib.config.ts
  e2e/cases/auto-external/module-import-warn/src/index.ts
  e2e/cases/externals/index.test.ts
  e2e/cases/externals/module-import-warn/rslib.config.ts
  e2e/cases/externals/module-import-warn/src/index.ts
  e2e/cases/externals/node/rslib.config.ts
  e2e/cases/externals/node/src/index.ts
  e2e/package.json
  e2e/scripts/helper.ts
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#130 feat: support default extensionAlias
  e2e/cases/extension-alias/__snapshots__/index.test.ts.snap
  e2e/cases/extension-alias/index.test.ts
  e2e/cases/extension-alias/package.json
  e2e/cases/extension-alias/rslib.config.ts
  e2e/cases/extension-alias/src/bar.js
  e2e/cases/extension-alias/src/foo.ts
  e2e/cases/extension-alias/src/index.ts
  e2e/cases/extension-alias/tsconfig.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: feat

#132 fix: add extension when relative import already have an extension
  e2e/cases/bundle-false/index.test.ts
  e2e/cases/bundle-false/relative-import/src/baz.js.ts
  e2e/cases/bundle-false/relative-import/src/foo.js
  e2e/cases/bundle-false/relative-import/src/index.ts
  e2e/cases/bundle-false/relative-import/src/qux.cjs
  packages/core/src/config.ts
Labels: change: fix

#127 feat: add default minify config
  CONTRIBUTING.md
  e2e/cases/alias/__snapshots__/index.test.ts.snap
  e2e/cases/auto-extension/index.test.ts
  e2e/cases/extension-alias/__snapshots__/index.test.ts.snap
  e2e/cases/minify/default/rslib.config.ts
  e2e/cases/minify/default/src/index.ts
  e2e/cases/minify/index.test.ts
  e2e/cases/shims/esm/src/index.ts
  e2e/cases/shims/index.test.ts
  e2e/cases/syntax/__snapshots__/index.test.ts.snap
  package.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
Labels: change: feat

#135 feat: modify merge config order
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/config.test.ts
Labels: change: feat

#146 docs: add SECURITY.md
  SECURITY.md
Labels: change: docs

#145 feat: setup `create-rslib` package
  .gitignore
  packages/create-rslib/LICENSE
  packages/create-rslib/README.md
  packages/create-rslib/package.json
  packages/create-rslib/rslib.config.ts
  packages/create-rslib/src/index.ts
  packages/create-rslib/template-common/README.md
  packages/create-rslib/template-common/gitignore
  packages/create-rslib/template-example-js/package.json
  packages/create-rslib/template-example-js/rslib.config.mjs
  packages/create-rslib/template-example-js/src/index.js
  packages/create-rslib/template-example-ts/package.json
  packages/create-rslib/template-example-ts/rslib.config.ts
  packages/create-rslib/template-example-ts/src/index.ts
  packages/create-rslib/template-example-ts/tsconfig.json
  packages/create-rslib/test/helper.ts
  packages/create-rslib/test/index.test.ts
  packages/create-rslib/tsconfig.json
  packages/create-rslib/vitest.config.ts
  pnpm-lock.yaml
Labels: change: feat

#144 fix: warn should handles all externals config
  e2e/cases/externals/index.test.ts
  e2e/cases/externals/module-import-warn/rslib.config.ts
  e2e/cases/externals/module-import-warn/src/baz.ts
  e2e/cases/externals/module-import-warn/src/index.ts
  packages/core/src/config.ts
  scripts/dictionary.txt
Labels: change: fix
