Repository web-infra-dev/rslib, pull requests merged in 2024-10, with the labels that each got.

#256 fix: use ESM chunkLoading for "esm" format
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
  tests/integration/async-chunks/default/package.json
  tests/integration/async-chunks/default/rslib.config.ts
  tests/integration/async-chunks/default/src/dynamic.js
  tests/integration/async-chunks/default/src/index.js
  tests/integration/async-chunks/index.test.ts
Labels: change: fix

#264 fix(dts): disable autoExtension for dts by default
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  tests/integration/dts/__snapshots__/index.test.ts.snap
  tests/integration/dts/bundle-false/auto-extension/rslib.config.ts
  tests/integration/dts/bundle-false/basic/rslib.config.ts
  tests/integration/dts/bundle/auto-extension/rslib.config.ts
  tests/integration/dts/bundle/basic/rslib.config.ts
  tests/integration/dts/index.test.ts
Labels: change: fix

#266 fix: count in `optionalDependencies` in `autoExternal`.
  packages/core/src/config.ts
  packages/core/src/types/utils.ts
  packages/plugin-dts/src/dts.ts
Labels: change: fix

#275 fix: inline `import.meta.url` shims in CJS
  packages/core/src/plugins/cjsShim.ts
  tests/integration/require/index.test.ts
  tests/integration/shims/cjs/src/index.ts
  tests/integration/shims/index.test.ts
Labels: change: fix

#282 fix(shim): use `module.require` to avoid variable collision
  packages/core/src/plugins/cjsShim.ts
  tests/integration/shims/cjs/rslib.config.ts
  tests/integration/shims/cjs/src/index.ts
  tests/integration/shims/cjs/src/ok.cjs
  tests/integration/shims/index.test.ts
  tests/tsconfig.json
Labels: change: fix

#288 fix: pass in projectReferences to avoid missing some error reports
  .changeset/proud-sheep-end.md
  packages/plugin-dts/src/tsc.ts
Labels: change: fix

#290 fix(deps): unpin Rsbuild to allow automatic patch upgrade
  examples/react-component-bundle/package.json
  packages/core/package.json
  packages/plugin-dts/package.json
  pnpm-lock.yaml
  tests/integration/asset/svgr/package.json
  tests/package.json
  website/package.json
Labels: change: fix

#291 feat!: add shims config
  .npmrc
  package.json
  packages/core/src/config.ts
  packages/core/src/plugins/shims.ts
  packages/core/src/types/config/index.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  tests/benchmark/index.bench.ts
  tests/integration/alias/index.test.ts
  tests/integration/asset/index.test.ts
  tests/integration/async-chunks/index.test.ts
  tests/integration/auto-extension/index.test.ts
  tests/integration/auto-external/index.test.ts
  tests/integration/banner-footer/index.test.ts
  tests/integration/bundle-false/index.test.ts
  tests/integration/copy/index.test.ts
  tests/integration/decorators/index.test.ts
  tests/integration/define/index.test.ts
  tests/integration/dts/index.test.ts
  tests/integration/entry/index.test.ts
  tests/integration/extension-alias/index.test.ts
  tests/integration/external-helpers/index.test.ts
  tests/integration/externals/index.test.ts
  tests/integration/minify/index.test.ts
  tests/integration/require/index.test.ts
  tests/integration/require/require-resolve/other.ts
  tests/integration/resolve/index.test.ts
  tests/integration/shims/cjs/rslib.config.ts
  tests/integration/shims/cjs/src/index.ts
  tests/integration/shims/esm/rslib.config.ts
  tests/integration/shims/esm/rslibShimsDisabled.config.ts
  tests/integration/shims/esm/src/index.ts
  tests/integration/shims/esm/src/ok.cjs
  tests/integration/shims/esm/src/require.ts
  tests/integration/shims/index.test.ts
  tests/integration/sourcemap/index.test.ts
  tests/integration/style/css-modules/index.test.ts
  tests/integration/style/css/index.test.ts
  tests/integration/style/less/index.test.ts
  tests/integration/style/lightningcss/index.test.ts
  tests/integration/style/postcss/index.test.ts
  tests/integration/style/redirect-style-false/index.test.ts
  tests/integration/style/sass/index.test.ts
  tests/integration/style/style-inject/index.test.ts
  tests/integration/style/tailwindcss/index.test.ts
  tests/integration/syntax/index.test.ts
  tests/integration/transform-import/index.test.ts
  tests/integration/tsconfig/index.test.ts
  tests/scripts/shared.ts
  website/docs/en/_meta.json
  website/docs/en/config/_meta.json
  website/docs/en/config/index.mdx
  website/docs/en/config/lib/shims.mdx
Labels: change: feat

#301 fix: correct ECMA version browserslist mapping
  packages/core/src/utils/syntax.ts
  packages/core/tests/config.test.ts
  packages/core/tests/syntax.test.ts
  tests/integration/syntax/__fixtures__/src/foo.ts
  tests/integration/syntax/__fixtures__/src/index.ts
  tests/integration/syntax/__snapshots__/index.test.ts.snap
Labels: change: fix

#307 perf(deps): replace fast-glob with tinyglobby
  packages/core/package.json
  packages/core/prebundle.config.mjs
  packages/core/rslib.config.ts
  packages/core/src/config.ts
  packages/core/tsconfig.json
  packages/plugin-dts/package.json
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  tests/package.json
  tests/scripts/helper.ts
Labels: change: perf

#309 docs: change enhanced to dev dep
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/zh/guide/advanced/module-federation.mdx
Labels: change: docs

#314 docs: add quick start doc
  website/docs/en/guide/start/quick-start.mdx
Labels: change: docs

#318 feat: support node polyfill
  biome.json
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  pnpm-lock.yaml
  scripts/dictionary.txt
  tests/README.md
  tests/integration/node-polyfill/bundle-false/package.json
  tests/integration/node-polyfill/bundle-false/rslib.config.ts
  tests/integration/node-polyfill/bundle-false/src/buffer1.ts
  tests/integration/node-polyfill/bundle-false/src/buffer2.ts
  tests/integration/node-polyfill/bundle-false/src/index.ts
  tests/integration/node-polyfill/bundle-false/tsconfig.json
  tests/integration/node-polyfill/bundle/package.json
  tests/integration/node-polyfill/bundle/rslib.config.ts
  tests/integration/node-polyfill/bundle/src/buffer1.ts
  tests/integration/node-polyfill/bundle/src/buffer2.ts
  tests/integration/node-polyfill/bundle/src/index.ts
  tests/integration/node-polyfill/bundle/tsconfig.json
  tests/integration/node-polyfill/index.test.ts
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/node-polyfill.mdx
Labels: change: feat

#320 docs: add introduction and features doc
  README.md
  website/docs/en/guide/start/index.mdx
Labels: change: docs

#323 fix: map syntax "es6" to "es2015"
  packages/core/src/utils/syntax.ts
  packages/core/tests/syntax.test.ts
Labels: change: fix

#325 feat: support set `dts: true` and dts default to bundleless
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/create-rslib/template-node-dual-ts/rslib.config.ts
  packages/create-rslib/template-node-esm-ts/rslib.config.ts
  pnpm-lock.yaml
  tests/integration/dts/bundle-false/true/package.json
  tests/integration/dts/bundle-false/true/rslib.config.ts
  tests/integration/dts/bundle/true/package.json
  tests/integration/dts/bundle/true/rslib.config.ts
  tests/integration/dts/index.test.ts
  tests/scripts/shared.ts
Labels: change: feat

#327 docs: add npm packages docs
  packages/plugin-dts/package.json
  website/docs/en/guide/start/npm-packages.mdx
Labels: change: docs

#329 docs: update node-polyfill.mdx
  website/docs/en/guide/advanced/node-polyfill.mdx
Labels: change: docs

#328 fix: "mf" format output should be minified by default
  examples/module-federation/mf-host/package.json
  examples/module-federation/mf-react-component/package.json
  examples/module-federation/mf-remote/package.json
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/minify/__fixtures__/src/index.ts
  tests/integration/minify/config/rslib.config.ts
  tests/integration/minify/default/rslib.config.ts
  tests/integration/minify/default/src/index.ts
  tests/integration/minify/index.test.ts
  tests/integration/minify/mf/config/package.json
  tests/integration/minify/mf/config/rslib.config.ts
  tests/integration/minify/mf/default/package.json
  tests/integration/minify/mf/default/rslib.config.ts
  tests/package.json
  tests/scripts/shared.ts
Labels: change: fix

#331 fix: use global as mf format external type
  packages/core/src/config.ts
Labels: change: fix

#335 fix: should emit config file parsing diagnostics in DTS build
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
Labels: change: fix

#337 feat: support `tsc --build` to incremental build project references
  packages/core/src/config.ts
  packages/core/src/types/config/index.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
  tests/README.md
  tests/integration/dts/composite/__references__/package.json
  tests/integration/dts/composite/__references__/src/index.ts
  tests/integration/dts/composite/__references__/tsconfig.json
  tests/integration/dts/composite/abort-on-error/package.json
  tests/integration/dts/composite/abort-on-error/rslib.config.ts
  tests/integration/dts/composite/abort-on-error/src/const.ts
  tests/integration/dts/composite/abort-on-error/src/index.ts
  tests/integration/dts/composite/abort-on-error/tsconfig.json
  tests/integration/dts/composite/basic/package.json
  tests/integration/dts/composite/basic/rslib.config.ts
  tests/integration/dts/composite/basic/src/index.ts
  tests/integration/dts/composite/basic/src/sum.ts
  tests/integration/dts/composite/basic/tsconfig.json
  tests/integration/dts/composite/dist-path/package.json
  tests/integration/dts/composite/dist-path/rslib.config.ts
  tests/integration/dts/composite/dist-path/src/index.ts
  tests/integration/dts/composite/dist-path/tsconfig.json
  tests/integration/dts/composite/process-files/package.json
  tests/integration/dts/composite/process-files/rslib.config.ts
  tests/integration/dts/composite/process-files/src/index.ts
  tests/integration/dts/composite/process-files/tsconfig.json
  tests/integration/dts/composite/tsconfig/package.json
  tests/integration/dts/composite/tsconfig/rslib.config.ts
  tests/integration/dts/composite/tsconfig/src/index.ts
  tests/integration/dts/composite/tsconfig/src/sum.ts
  tests/integration/dts/composite/tsconfig/tsconfig.json
  tests/integration/dts/index.test.ts
Labels: change: feat

#347 docs: add license to website footer
  website/rspress.config.ts
  website/theme/components/Copyright.tsx
Labels: change: docs

#346 fix(create-rslib): preserve @rslib/core as workspace
  packages/create-rslib/fragments/tools/vitest-react-js/package.json
  packages/create-rslib/fragments/tools/vitest-react-ts/package.json
  packages/create-rslib/src/helpers.ts
  packages/create-rslib/template-[node-dual]-[]-js/package.json
  packages/create-rslib/template-[node-dual]-[]-ts/package.json
  packages/create-rslib/template-[node-dual]-[vitest]-js/package.json
  packages/create-rslib/template-[node-dual]-[vitest]-ts/package.json
  packages/create-rslib/template-[node-esm]-[]-js/package.json
  packages/create-rslib/template-[node-esm]-[]-ts/package.json
  packages/create-rslib/template-[node-esm]-[vitest]-js/package.json
  packages/create-rslib/template-[node-esm]-[vitest]-ts/package.json
  packages/create-rslib/template-[react]-[]-js/package.json
  packages/create-rslib/template-[react]-[]-ts/package.json
  packages/create-rslib/template-[react]-[storybook,vitest]-js/package.json
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/package.json
  packages/create-rslib/template-[react]-[storybook]-js/package.json
  packages/create-rslib/template-[react]-[storybook]-ts/package.json
  packages/create-rslib/template-[react]-[vitest]-js/package.json
  packages/create-rslib/template-[react]-[vitest]-ts/package.json
Labels: change: fix
