Repository web-infra-dev/rslib, pull requests merged in 2025-02, with the labels that each got.

#721 docs: minor edits to en docs
  website/docs/en/guide/solution/index.mdx
  website/docs/en/guide/solution/nodejs.mdx
  website/docs/en/guide/start/index.mdx
  website/docs/en/guide/start/quick-start.mdx
Labels: change: docs

#725 docs: patch necessary changes
  website/docs/en/guide/solution/nodejs.mdx
  website/docs/en/guide/start/quick-start.mdx
Labels: change: docs

#732 docs: remove placeholder docs
  website/docs/en/api/_meta.json
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/types.mdx
  website/docs/en/config/lib/bundle.mdx
  website/docs/en/guide/advanced/assets.mdx
  website/docs/en/guide/advanced/css.mdx
  website/docs/en/guide/advanced/module-doc.mdx
  website/docs/en/guide/advanced/monorepo.mdx
  website/docs/en/guide/faq/exceptions.mdx
  website/docs/en/guide/faq/general.mdx
  website/docs/en/guide/migration/esbuild.mdx
  website/docs/en/guide/migration/rollup.mdx
  website/docs/en/guide/solution/index.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/config/lib/bundle.mdx
  website/docs/zh/guide/advanced/assets.mdx
  website/docs/zh/guide/advanced/css.mdx
  website/docs/zh/guide/advanced/module-doc.mdx
  website/docs/zh/guide/advanced/monorepo.mdx
  website/docs/zh/guide/faq/exceptions.mdx
  website/docs/zh/guide/faq/general.mdx
  website/docs/zh/guide/migration/esbuild.mdx
  website/docs/zh/guide/migration/rollup.mdx
  website/docs/zh/guide/solution/index.mdx
  website/docs/zh/guide/start/features.mdx
Labels: change: docs

#735 docs: update rspress 1.41.0 and enable codeBlocks search
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
Labels: change: docs

#737 docs: add bundleless mode img and polish the some words
  website/docs/en/config/lib/bundle.mdx
  website/docs/en/guide/basic/output-structure.mdx
  website/docs/zh/config/lib/bundle.mdx
  website/docs/zh/config/lib/syntax.mdx
  website/docs/zh/guide/basic/output-structure.mdx
Labels: change: docs

#739 feat(core): reexport "@rslib/core/types" from "@rsbuild/core/types"
  examples/preact-component-bundle-false/src/env.d.ts
  examples/react-component-bundle-false/src/env.d.ts
  examples/react-component-bundle/src/env.d.ts
  examples/react-component-umd/src/env.d.ts
  packages/core/package.json
  packages/core/tsconfig.json
  packages/core/types.d.ts
  website/docs/en/guide/migration/modernjs-module.mdx
  website/docs/zh/guide/migration/modernjs-module.mdx
Labels: change: feat

#740 fix(dts): correct tsconfig path not found error message
  packages/plugin-dts/src/index.ts
  pnpm-lock.yaml
  tests/integration/dts/bundle-false/tsconfig-path/package.json
  tests/integration/dts/bundle-false/tsconfig-path/rslib.config.ts
  tests/integration/dts/index.test.ts
Labels: change: fix

#742 feat: support DTS redirect
  packages/core/src/config.ts
  packages/core/src/types/config.ts
  packages/plugin-dts/README.md
  packages/plugin-dts/package.json
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/tsc.ts
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
  tests/integration/redirect/dts.test.ts
  tests/integration/redirect/dts/compile/rslog/index.d.ts
  tests/integration/redirect/dts/compile/rslog/index.js
  tests/integration/redirect/dts/compile/rslog/package.json
  tests/integration/redirect/dts/package.json
  tests/integration/redirect/dts/rslib.config.ts
  tests/integration/redirect/dts/src/foo/foo.ts
  tests/integration/redirect/dts/src/index.ts
  tests/integration/redirect/dts/src/logger.ts
  tests/integration/redirect/dts/src/types.ts
  tests/integration/redirect/dts/tsconfig.json
  website/docs/en/config/lib/redirect.mdx
  website/docs/en/guide/migration/modernjs-module.mdx
  website/docs/zh/config/lib/redirect.mdx
  website/docs/zh/guide/basic/typescript.mdx
  website/docs/zh/guide/migration/modernjs-module.mdx
Labels: change: feat

#746 fix: windows issue in dts redirect
  packages/plugin-dts/src/utils.ts
Labels: change: fix

#745 feat: support outBase config
  packages/core/src/config.ts
  packages/core/src/types/config.ts
  pnpm-lock.yaml
  tests/integration/outBase/custom-entry/package.json
  tests/integration/outBase/custom-entry/rslib.config.ts
  tests/integration/outBase/custom-entry/src/bar/index.ts
  tests/integration/outBase/custom-entry/src/utils/foo/index.ts
  tests/integration/outBase/custom-entry/src/utils/index.ts
  tests/integration/outBase/index.test.ts
  tests/integration/outBase/nested-dir/package.json
  tests/integration/outBase/nested-dir/rslib.config.ts
  tests/integration/outBase/nested-dir/src/utils/bar/index.ts
  tests/integration/outBase/nested-dir/src/utils/foo/index.ts
  tests/integration/outBase/nested-dir/src/utils/index.ts
  website/docs/en/config/lib/_meta.json
  website/docs/en/config/lib/out-base.mdx
  website/docs/en/guide/migration/tsup.mdx
  website/docs/zh/config/lib/_meta.json
  website/docs/zh/config/lib/bundle.mdx
  website/docs/zh/config/lib/out-base.mdx
  website/docs/zh/guide/migration/tsup.mdx
Labels: change: feat

#751 docs: display GitHub button on homepage
  pnpm-lock.yaml
  website/package.json
  website/theme/components/Hero.tsx
Labels: change: docs

#752 fix: clean dts distPath earlier
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  pnpm-lock.yaml
  tests/integration/dts/copy/copy.d.ts
  tests/integration/dts/copy/package.json
  tests/integration/dts/copy/rslib.config.ts
  tests/integration/dts/copy/src/index.ts
  tests/integration/dts/copy/tsconfig.json
  tests/integration/dts/index.test.ts
Labels: change: fix

#754 fix: correct detect transformed module external request
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/auto-external/index.test.ts
  tests/integration/auto-external/module-import-warn/package.json
  tests/integration/auto-external/module-import-warn/rslib.config.ts
  tests/integration/auto-external/module-import-warn/src/index.ts
Labels: change: fix

#760 fix(bundleless): only try to redirect files under outBase dir
  packages/core/src/config.ts
  tests/integration/bundle-false/basic/.gitignore
  tests/integration/bundle-false/basic/node_modules/dep_add/index.d.ts
  tests/integration/bundle-false/basic/node_modules/dep_add/index.js
  tests/integration/bundle-false/basic/node_modules/dep_add/package.json
  tests/integration/bundle-false/basic/src/dep.ts
  tests/integration/bundle-false/basic/src/index.ts
  tests/integration/bundle-false/index.test.ts
Labels: change: fix

#741 docs(assets): add assets, json, svgr usage document
  tests/integration/asset/__snapshots__/index.test.ts.snap
  tests/integration/asset/json/src/index.js
  website/docs/en/config/rsbuild/output.mdx
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/json-files.mdx
  website/docs/en/guide/advanced/static-assets.mdx
  website/docs/en/guide/advanced/svgr-files.mdx
  website/docs/zh/config/rsbuild/output.mdx
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/advanced/json-files.mdx
  website/docs/zh/guide/advanced/static-assets.mdx
  website/docs/zh/guide/advanced/svgr-files.mdx
  website/docs/zh/guide/solution/index.mdx
Labels: change: docs

#755 docs: add why Rslib chapter
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#763 docs: add bundleless externals note
  website/docs/en/config/rsbuild/resolve.mdx
  website/docs/zh/config/rsbuild/resolve.mdx
Labels: change: docs

#767 fix(CI): should filter workspaces in pkg-pr-new
  .github/workflows/preview.yml
Labels: change: fix

#771 docs: modify examples of `redirect.dts.extension`
  packages/plugin-dts/README.md
  website/docs/en/config/lib/redirect.mdx
  website/docs/zh/config/lib/redirect.mdx
Labels: change: docs

#778 fix: redirect index file when `redirect.dts.extension` is enabled
  packages/plugin-dts/src/utils.ts
  tests/integration/redirect/dts.test.ts
  tests/integration/redirect/dts/src/foo/index.ts
  tests/integration/redirect/dts/src/index.ts
Labels: change: fix

#780 feat: warn if `declarationDir` or `outDir` is resolved outside project root
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
  tests/integration/dts/check/outside-root/package.json
  tests/integration/dts/check/outside-root/rslib.config.ts
  tests/integration/dts/check/outside-root/src/index.ts
  tests/integration/dts/check/outside-root/tsconfig.json
  tests/integration/dts/check/tsconfig/declarationDir.json
  tests/integration/dts/index.test.ts
Labels: change: feat

#788 fix: revert dtsEmitPath generate logic to respect `output.distPath.root`
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/utils.ts
  packages/plugin-dts/tests/dts.test.ts
Labels: change: fix

#789 docs: enhance entry exclusion in bundleless mode
  website/docs/en/config/lib/bundle.mdx
  website/docs/zh/config/lib/bundle.mdx
Labels: change: docs

#793 feat: support bundle DTS of multiple entries
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
  packages/plugin-dts/src/index.ts
  packages/plugin-dts/src/utils.ts
  pnpm-lock.yaml
  tests/integration/dts/__snapshots__/index.test.ts.snap
  tests/integration/dts/bundle/multiple-entries/package.json
  tests/integration/dts/bundle/multiple-entries/rslib.config.ts
  tests/integration/dts/index.test.ts
  website/docs/en/config/lib/dts.mdx
  website/docs/zh/config/lib/dts.mdx
Labels: change: feat

#795 docs: add SVGR in React solution
  packages/core/src/asset/assetConfig.ts
  packages/plugin-dts/src/dts.ts
  tests/integration/style/less/bundle-false/rslib.config.ts
  website/docs/en/guide/solution/react.mdx
  website/docs/zh/guide/solution/react.mdx
Labels: change: docs

#796 docs: correct `externalHelpers` highlights
  website/docs/en/config/lib/external-helpers.mdx
  website/docs/zh/config/lib/external-helpers.mdx
Labels: change: docs

#797 docs: add `README.zh-CN.md` and update some chapters
  README.md
  README.zh-CN.md
  packages/core/package.json
  packages/plugin-dts/package.json
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#805 docs: modify description of `resolve.alias`
  website/docs/en/config/rsbuild/resolve.mdx
  website/docs/zh/config/rsbuild/resolve.mdx
Labels: change: docs
