Repository web-infra-dev/rslib, pull requests merged in 2025-01, with the labels that each got.

#636 fix: do not treat .d.ts as entry
  packages/core/src/constant.ts
  packages/core/tests/constant.test.ts
  tests/integration/entry/glob/src/global.d.ts
Labels: change: fix

#634 fix: detect possible glob pattern in bundle more
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/entry/glob-bundle/package.json
  tests/integration/entry/glob-bundle/rslib.config.ts
  tests/integration/entry/glob-bundle/src/bar.ts
  tests/integration/entry/glob-bundle/src/foo.ts
  tests/integration/entry/index.test.ts
Labels: change: fix

#618 feat!: support `redirect.style.path` and `redirect.style.extension`
  packages/core/src/config.ts
  packages/core/src/css/cssConfig.ts
  packages/core/src/types/config.ts
  pnpm-lock.yaml
  tests/integration/redirect/style-false/rslib.config.ts
  tests/integration/redirect/style-false/src/index.ts
  tests/integration/redirect/style.test.ts
  tests/integration/redirect/style/package.json
  tests/integration/redirect/style/rslib.config.ts
  tests/integration/redirect/style/src/less/index.less
  tests/integration/redirect/style/src/less/index.ts
  tests/integration/redirect/style/src/module/index.module.less
  tests/integration/redirect/style/src/module/index.ts
  tests/integration/redirect/style/tsconfig.json
  website/docs/en/config/lib/auto-extension.mdx
  website/docs/en/config/lib/redirect.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/config/lib/auto-extension.mdx
  website/docs/zh/config/lib/redirect.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: change: feat

#642 fix: handle add and unlink file in bundleless mode
  packages/core/src/config.ts
  packages/core/src/plugins/EntryChunkPlugin.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  tests/integration/cli/build-watch/build.test.ts
  tests/integration/cli/build-watch/rslib.config.ts
  tests/integration/cli/build-watch/src/index.ts
  tests/integration/directive/index.test.ts
  tests/integration/directive/react/bundleless/rslib.config.ts
  tests/scripts/helper.ts
Labels: change: fix

#647 feat: entry default to `src/**` in bundleless mode
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/entry/default/package.json
  tests/integration/entry/default/rslib.config.ts
  tests/integration/entry/default/src/foo.ts
  tests/integration/entry/default/src/index.ts
  tests/integration/entry/index.test.ts
  website/docs/en/config/lib/bundle.mdx
  website/docs/en/config/rsbuild/source.mdx
  website/docs/zh/config/lib/bundle.mdx
  website/docs/zh/config/rsbuild/source.mdx
Labels: change: feat

#648 feat: throw error when no configuration match `--lib` option
  packages/core/src/cli/mf.ts
  packages/core/src/config.ts
  tests/integration/cli/build/build.test.ts
  tests/integration/cli/mf/mf.test.ts
Labels: change: feat

#651 docs: introduce the different default values between Rslib and Rsbuild
  website/docs/en/config/rsbuild/output.mdx
  website/docs/en/config/rsbuild/source.mdx
  website/docs/zh/config/rsbuild/output.mdx
  website/docs/zh/config/rsbuild/source.mdx
Labels: change: docs

#653 fix: user externals should have higher priority
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/externals/index.test.ts
  tests/integration/externals/user-externals/package.json
  tests/integration/externals/user-externals/rslib.config.ts
  tests/integration/externals/user-externals/src/foo.js
  tests/integration/externals/user-externals/src/index.js
Labels: change: fix

#658 docs: how to migrate from existing projects
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#668 fix: edge case of dts RegExp
  packages/core/src/constant.ts
  packages/core/tests/constant.test.ts
Labels: change: fix

#671 docs: unify title capitalization style
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  examples/module-federation/mf-remote/README.md
  packages/create-rslib/template-common/README.md
  website/README.md
  website/docs/en/api/javascript-api/core.mdx
  website/docs/en/api/javascript-api/types.mdx
  website/docs/en/config/lib/auto-extension.mdx
  website/docs/en/config/lib/auto-external.mdx
  website/docs/en/config/lib/banner.mdx
  website/docs/en/config/lib/bundle.mdx
  website/docs/en/config/lib/dts.mdx
  website/docs/en/config/lib/footer.mdx
  website/docs/en/config/lib/id.mdx
  website/docs/en/config/lib/index.mdx
  website/docs/en/config/lib/syntax.mdx
  website/docs/en/config/rsbuild/index.mdx
  website/docs/en/config/rsbuild/plugins.mdx
  website/docs/en/guide/advanced/dts.mdx
  website/docs/en/guide/advanced/module-doc.mdx
  website/docs/en/guide/advanced/module-federation.mdx
  website/docs/en/guide/advanced/output-compatibility.mdx
  website/docs/en/guide/advanced/storybook.mdx
  website/docs/en/guide/advanced/third-party-deps.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/configure-rslib.mdx
  website/docs/en/guide/basic/output-format.mdx
  website/docs/en/guide/basic/output-structure.mdx
  website/docs/en/guide/basic/typescript.mdx
  website/docs/en/guide/basic/upgrade-rslib.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/en/guide/migration/modernjs-module.mdx
  website/docs/en/guide/migration/tsup.mdx
  website/docs/en/guide/solution/index.mdx
  website/docs/en/guide/solution/nodejs.mdx
  website/docs/en/guide/solution/react.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/config/lib/syntax.mdx
  website/docs/zh/guide/advanced/dts.mdx
  website/docs/zh/guide/solution/index.mdx
  website/docs/zh/guide/solution/react.mdx
Labels: change: docs

#677 fix: only treat files within context as source file
  packages/core/src/config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  tests/integration/asset/limit/assets/logo.svg
  tests/integration/asset/limit/src/index.js
  tests/integration/asset/name/assets/image.png
  tests/integration/asset/name/src/index.jsx
  tests/integration/asset/path/assets/image.png
  tests/integration/asset/path/src/index.js
  tests/integration/asset/public-path/assets/logo.svg
  tests/integration/asset/public-path/src/index.js
  tests/integration/asset/svgr/assets/logo.svg
  tests/integration/asset/svgr/src/index.js
  tests/integration/asset/svgr/src/namedExport.js
  tests/integration/bundle-false/asset/assets/image.png
  tests/integration/bundle-false/asset/assets/logo.svg
  tests/integration/bundle-false/asset/src/index.js
  tests/integration/bundle-false/index.test.ts
  tests/integration/bundle-false/monorepo/importee/index.js
  tests/integration/bundle-false/monorepo/importee/package.json
  tests/integration/bundle-false/monorepo/importer/package.json
  tests/integration/bundle-false/monorepo/importer/rslib.config.ts
  tests/integration/bundle-false/monorepo/importer/src/index.js
  tests/integration/bundle-false/svgr/assets/logo.svg
  tests/integration/bundle-false/svgr/src/index.jsx
  tests/integration/redirect/js-not-resolve/src/index.js
  tests/integration/redirect/js.test.ts
  tests/integration/redirect/js/src/index.ts
  tests/integration/redirect/jsNotResolved.test.ts
  tests/integration/style/css-modules/bundle-false-auto/rslib.config.ts
  tests/integration/style/less/bundle-false/rslib.config.ts
  tests/integration/style/less/bundle-import/rslib.config.ts
  tests/integration/style/less/bundle/rslib.config.ts
  tests/integration/style/sass/bundle-false/rslib.config.ts
Labels: change: fix

#685 fix: validate entry type
  packages/core/src/config.ts
  tests/integration/entry/index.test.ts
  tests/integration/entry/validate/bundlelessWithString.config.ts
  website/docs/en/config/rsbuild/source.mdx
  website/docs/zh/config/rsbuild/source.mdx
Labels: change: fix

#698 fix: emit css source map in bundleless mode
  examples/react-component-bundle-false/rslib.config.ts
  packages/core/src/css/libCssExtractLoader.ts
  pnpm-lock.yaml
  tests/integration/sourcemap/css/package.json
  tests/integration/sourcemap/css/rslib.config.ts
  tests/integration/sourcemap/css/src/index.css
  tests/integration/sourcemap/index.test.ts
Labels: change: fix

#702 fix: use pre hook order to promise dts task
  packages/plugin-dts/src/index.ts
Labels: change: fix

#705 feat(asset): support svgr exportType usage
  packages/core/src/asset/assetConfig.ts
  tests/integration/asset/__snapshots__/index.test.ts.snap
  tests/integration/asset/index.test.ts
  tests/integration/asset/svgr/rslib.config.ts
  tests/integration/asset/svgr/src/assets/logo2.svg
Labels: change: feat

#706 docs(QA): add how to external module in DTS
  website/docs/en/guide/faq/features.mdx
  website/docs/zh/guide/faq/features.mdx
Labels: change: docs

#712 feat: support banner and footer in bundleless emitted css
  packages/core/src/config.ts
  packages/core/src/css/cssConfig.ts
  packages/core/src/css/libCssExtractLoader.ts
  tests/integration/banner-footer/rslib.config.ts
  tests/integration/banner-footer/src/index.ts
  tests/integration/style/css-modules/index.test.ts
  tests/integration/style/stylus/index.test.ts
Labels: change: feat

#715 fix: warn duplicate entries in bundleless mode
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/entry/duplicate/package.json
  tests/integration/entry/duplicate/rslib.config.ts
  tests/integration/entry/duplicate/src/index.css
  tests/integration/entry/duplicate/src/index.module.css
  tests/integration/entry/duplicate/src/index.svg
  tests/integration/entry/duplicate/src/index.ts
  tests/integration/entry/index.test.ts
Labels: change: fix
