Repository web-infra-dev/rslib, pull requests merged in 2025-03, with the labels that each got.

#818 fix: `output.filenameHash` does not take effect on JavaScript files
  packages/core/src/config.ts
  tests/integration/auto-extension/index.test.ts
  tests/integration/auto-extension/type-commonjs/config-override/rslib.config.ts
  tests/integration/auto-extension/type-module/config-override/rslib.config.ts
  website/docs/en/config/rsbuild/output.mdx
  website/docs/zh/config/rsbuild/output.mdx
Labels: change: fix

#820 fix: should check lib array non-empty
  packages/core/src/config.ts
  pnpm-lock.yaml
  tests/integration/config-check/index.test.ts
  tests/integration/config-check/lib-array/package.json
  tests/integration/config-check/lib-array/rslib.config.ts
Labels: change: fix

#833 docs: fix typo
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#835 docs: align theme colors with Rspack
  website/docs/en/guide/start/quick-start.mdx
  website/theme/index.scss
Labels: change: docs

#840 docs: polish bundleless glossary
  package.json
  website/docs/en/guide/basic/output-structure.mdx
  website/docs/en/guide/faq/features.mdx
  website/docs/en/guide/start/glossary.mdx
  website/docs/zh/guide/basic/output-structure.mdx
  website/docs/zh/guide/start/glossary.mdx
Labels: change: docs

#841 docs: add some default strategy of declaration files generation
  website/docs/en/guide/advanced/dts.mdx
  website/docs/zh/guide/advanced/dts.mdx
Labels: change: docs

#843 fix: standardize logging messages
  packages/core/__mocks__/rslog.cjs
  packages/core/src/cli/restart.ts
  packages/core/src/config.ts
  packages/core/src/utils/extension.ts
  packages/core/src/utils/helper.ts
  packages/core/src/utils/logger.ts
  packages/plugin-dts/src/utils.ts
  tests/integration/auto-external/index.test.ts
  tests/integration/externals/index.test.ts
Labels: change: fix

#846 fix: correct use contextDependencies
  packages/core/src/plugins/EntryChunkPlugin.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  tests/integration/cli/build-watch/build.test.ts
  tests/integration/cli/build-watch/rslib.config.ts
Labels: change: fix

#848 docs: apply new theme colors to the documentation site
  website/theme/index.scss
Labels: change: docs

#857 fix: override default values of some type descriptions
  packages/core/src/config.ts
  packages/core/src/types/config.ts
Labels: change: fix

#866 docs: enhance `output.assetPrefix`
  tests/integration/style/sass/bundle-false/rslib.config.ts
  website/docs/en/config/rsbuild/output.mdx
  website/docs/en/guide/advanced/static-assets.mdx
  website/docs/zh/config/rsbuild/output.mdx
  website/docs/zh/guide/advanced/static-assets.mdx
Labels: change: docs

#872 fix(dts): add missing `optionalDependencies` type
  packages/plugin-dts/src/index.ts
Labels: change: fix

#873 docs(json): add documents for YAML and TOML file support
  website/docs/en/guide/advanced/json-files.mdx
  website/docs/zh/guide/advanced/json-files.mdx
Labels: change: docs

#874 docs: fix Discord URL
  README.md
Labels: change: docs

#819 feat!: change to `commonjs-static` library type of commonjs format
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  tests/integration/alias/__snapshots__/index.test.ts.snap
  tests/integration/asset/__snapshots__/index.test.ts.snap
  tests/integration/asset/index.test.ts
  tests/integration/auto-extension/index.test.ts
  tests/integration/bundle-false/__snapshots__/index.test.ts.snap
  tests/integration/bundle-false/index.test.ts
  tests/integration/extension-alias/__snapshots__/index.test.ts.snap
  tests/integration/format/cjs-static-export/rslib.config.ts
  tests/integration/format/cjs-static-export/src/index.js
  tests/integration/format/cjs-static-export/src/value.js
  tests/integration/format/import-meta-url/rslib.config.ts
  tests/integration/format/import-meta-url/src/index.js
  tests/integration/format/import-meta-url/src/value.js
  tests/integration/format/index.test.ts
Labels: change: feat

#878 docs: add default module definition systems
  website/docs/en/config/lib/format.mdx
  website/docs/zh/config/lib/format.mdx
Labels: change: docs

#883 feat: export Rspack and Rsbuild
  packages/core/src/index.ts
Labels: change: feat

#890 fix: do not modify filename when `cssModules.auto: false`
  packages/core/src/config.ts
  packages/core/src/css/cssConfig.ts
  packages/core/src/css/libCssExtractLoader.ts
  pnpm-lock.yaml
  tests/integration/style/css-modules/__fixtures__/basic/src/button/index.module.scss
  tests/integration/style/css-modules/bundle-false-auto-false/package.json
  tests/integration/style/css-modules/bundle-false-auto-false/rslib.config.ts
  tests/integration/style/css-modules/index.test.ts
Labels: change: fix
