Repository web-infra-dev/rslib, pull requests merged in 2025-08, with the labels that each got.

#1146 docs: add llms copy button
  website/theme/index.tsx
Labels: change: docs

#1153 docs: add version badges to Rstack tools table
  README.md
  README.zh-CN.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#1156 fix(dts): should keep watch if bundle dts failed
  packages/plugin-dts/src/apiExtractor.ts
  packages/plugin-dts/src/dts.ts
Labels: change: fix

#1159 feat!: update minimum Node.js version to 18.12.0
  package.json
  packages/core/package.json
  packages/create-rslib/package.json
  packages/plugin-dts/package.json
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: feat

#1160 feat: update tsconfig.json and build configs to ES2022
  examples/module-federation/mf-host/tsconfig.json
  examples/module-federation/mf-remote/tsconfig.json
  examples/vue-component-bundle/tsconfig.json
  examples/vue-component-bundleless/tsconfig.json
  packages/core/rslib.config.ts
  packages/create-rslib/fragments/base/node-dual-ts/tsconfig.json
  packages/create-rslib/fragments/base/node-esm-ts/tsconfig.json
  packages/create-rslib/fragments/base/react-ts/tsconfig.json
  packages/create-rslib/fragments/base/vue-ts/tsconfig.json
  packages/create-rslib/rslib.config.ts
  packages/create-rslib/template-[node-dual]-[]-ts/tsconfig.json
  packages/create-rslib/template-[node-dual]-[vitest]-ts/tsconfig.json
  packages/create-rslib/template-[node-esm]-[]-ts/tsconfig.json
  packages/create-rslib/template-[node-esm]-[vitest]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[storybook,vitest]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[storybook]-ts/tsconfig.json
  packages/create-rslib/template-[react]-[vitest]-ts/tsconfig.json
  packages/create-rslib/template-[vue]-[]-ts/tsconfig.json
  packages/create-rslib/template-[vue]-[storybook,vitest]-ts/tsconfig.json
  packages/create-rslib/template-[vue]-[storybook]-ts/tsconfig.json
  packages/create-rslib/template-[vue]-[vitest]-ts/tsconfig.json
  packages/plugin-dts/rslib.config.ts
  scripts/tsconfig/base.json
  tests/e2e/react-component/tsconfig.json
Labels: change: feat

#1176 feat(dts): support emitting `.d.cts.map` and `.d.mts.map` files
  packages/plugin-dts/src/tsc.ts
  pnpm-lock.yaml
  tests/integration/dts/build/declaration-map/package.json
  tests/integration/dts/build/declaration-map/rslib.config.ts
  tests/integration/dts/build/declaration-map/src/index.ts
  tests/integration/dts/build/declaration-map/tsconfig.cjs.json
  tests/integration/dts/build/declaration-map/tsconfig.esm.json
  tests/integration/dts/bundle-false/declaration-map/package.json
  tests/integration/dts/bundle-false/declaration-map/rslib.config.ts
  tests/integration/dts/bundle-false/declaration-map/src/index.ts
  tests/integration/dts/bundle-false/declaration-map/tsconfig.json
  tests/integration/dts/composite/declaration-map/package.json
  tests/integration/dts/composite/declaration-map/rslib.config.ts
  tests/integration/dts/composite/declaration-map/src/index.ts
  tests/integration/dts/composite/declaration-map/tsconfig.json
  tests/integration/dts/index.test.ts
Labels: change: feat

#1177 docs: remove unnecessary paragraphs in modernjs-module migration docs
  website/docs/en/guide/migration/modernjs-module.mdx
  website/docs/zh/guide/migration/modernjs-module.mdx
Labels: change: docs

#1182 fix(css): prevent adding empty css rule
  packages/core/src/css/cssConfig.ts
  pnpm-lock.yaml
Labels: change: fix

#1194 feat: only split async chunks for umd format
  packages/core/src/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
Labels: change: feat

#1196 fix: should glob dot files in bundleless mode
  packages/core/src/config.ts
  tests/integration/bundle-false/basic/src/.hidden-folder/index.ts
  tests/integration/bundle-false/basic/src/.hidden.ts
  tests/integration/bundle-false/basic/src/index.ts
  tests/integration/bundle-false/index.test.ts
  tests/integration/redirect/dts.test.ts
  tests/integration/redirect/dts/src/.hidden-folder/index.ts
  tests/integration/redirect/dts/src/.hidden.ts
  tests/integration/redirect/dts/src/index.ts
  tests/integration/redirect/js.test.ts
  tests/integration/redirect/js/src/.hidden-folder/index.ts
  tests/integration/redirect/js/src/.hidden.ts
  tests/integration/redirect/js/src/index.ts
  tests/scripts/helper.ts
Labels: change: fix
